### ISSUE TITLE
[FEATURE] Automatic Project Discovery

### ISSUE THREAD

**Issue by jdrhyne** [jdrhyne/claude-code-github#24]
### Problem Statement
Currently, users must manually add each project to the configuration file. When working with multiple repositories or frequently creating new projects, this becomes tedious and error-prone.

### Proposed Solution
Implement automatic discovery of Git repositories within specified directories. The system would:
1. Scan designated folders for `.git` directories
2. Automatically detect repository information (remote URL, default branch)
3. Add discovered projects to the active monitoring list
4. Provide options to include/exclude specific repositories

### Use Cases
- Developers with many active projects in a workspace
- Teams where new repositories are frequently created
- CI/CD environments where projects are dynamically cloned

### Technical Approach
```yaml
# Proposed config structure
project_discovery:
  enabled: true
  scan_paths:
    - "/Users/admin/Projects"
    - "/Users/admin/Work"
  exclude_patterns:
    - "*/node_modules/*"
    - "*/archived/*"
  auto_detect_github_repo: true
```

### Benefits
- Reduced configuration overhead
- Automatic detection of new projects
- Less manual maintenance
- Better developer experience

### Potential Challenges
- Performance impact of scanning large directories
- Handling of nested git repositories
- Managing excluded patterns efficiently

### Alternatives Considered
Manual configuration remains available for users who prefer explicit control

### Additional Context
This feature would significantly improve the onboarding experience for new users and reduce friction for power users managing multiple projects.
