### ISSUE TITLE
[FEATURE] Parent Folder Monitoring with Auto-Detection

### ISSUE THREAD

**Issue by jdrhyne** [jdrhyne/claude-code-github#25]
### Problem Statement
Users working in a common workspace folder need to configure each project individually. When Claude Code is used across multiple projects in the same parent directory, manual configuration becomes repetitive.

### Proposed Solution
Enable monitoring of parent directories with automatic detection of Git repositories. The system would:
1. Monitor a parent folder (e.g., ~/Projects)
2. Automatically detect when entering a Git repository subdirectory
3. Apply smart defaults based on repository characteristics
4. Cache repository information for performance

### Use Cases
- Developers using Claude Code across multiple projects in a workspace
- Consultants switching between client projects
- Open source contributors working on multiple repositories

### Technical Approach
```yaml
# Proposed config structure
workspace_monitoring:
  enabled: true
  workspaces:
    - path: "/Users/admin/Projects"
      auto_detect: true
      inherit_settings: true
      cache_discovery: true
      github_repo_detection: "from_remote"  # or "from_folder_name"
```

### Benefits
- Zero configuration for new projects
- Seamless project switching
- Intelligent context awareness
- Reduced setup friction

### Potential Challenges
- Memory usage for monitoring multiple projects
- Handling of non-git folders
- Performance optimization for large workspaces
- Conflicting project-specific settings

### Alternatives Considered
- Symbolic link approach (requires manual setup)
- Script-based project addition (less seamless)

### Additional Context
This feature would make claude-code-github feel more like a native part of the development environment, automatically adapting to the user's current context without manual intervention.
